[[redirects]]
  from = "/couponscorpion"
  to = "https://couponscorpion.com/wp-json/wp/v2/posts"
  status = 200

 [[redirects]]
  from = "/onlinecourses"
  to = "https://onlinetutorials.org/wp-json/wp/v2/posts"
  status = 200