[[redirects]]
    from = "/wp-json/wp/v2/posts?per_page=80&_fields=title,modified,id,link&order=desc"
    to = "https://couponscorpion.com/wp-json/wp/v2/posts?per_page=80&_fields=title,modified,id,link&order=des"