[[redirects]]
  from = "/couponscorpion"
  to = "https://couponscorpion.com/wp-json/wp/v2/posts?per_page=80&_fields=title,modified,id,link&order=desc"
  status = 200

 [[redirects]] 
  from = "/onlinecourses"
  to = "https://onlinetutorials.org/wp-json/wp/v2/posts?per_page=80&_fields=title,modified,id,link&order=desc"
  status = 200